CREATE TABLE IF NOT EXISTS PAYMENTS
  ( PaymentId SERIAL PRIMARY KEY
  , Code VARCHAR(36) NOT NULL
  , Amount DECIMAL NOT NULL
  , CreateTimestamp TIMESTAMP NOT NULL
  , ProcessorId SMALLINT
  , CurrentServerId SMALLINT
  );

CREATE INDEX IF NOT EXISTS IX_PAYMENTS_BY_CREATETIME ON PAYMENTS (CreateTimestamp, ProcessorId);

CREATE TABLE IF NOT EXISTS PAYMENT_PLANS
  ( PlanId SERIAL PRIMARY KEY
  , PaymentId SERIAL REFERENCES PAYMENTS(PaymentId)
  , PlanServerId SMALLINT
  , PlanVersion SMALLINT NOT NULL
  , FireTimestamp TIMESTAMP NOT NULL
  );

CREATE INDEX IF NOT EXISTS IX_PLANS ON PLANS (PlanId, PaymentId);

INSERT INTO DB_VERSIONS (VersionCode) VALUES ('START');
