CREATE TABLE IF NOT EXISTS PAYMENTS
  ( PaymentId SERIAL PRIMARY KEY
  , Code VARCHAR(36) NOT NULL
  , Amount DECIMAL NOT NULL
  , CreateTimestamp TIMESTAMPZ NOT NULL
  , NextRetryTimestamp TIMESTAMPZ
  , Retries SMALLINT NOT NULL
  , Finished SMALLINT NOT NULL
  , ProcessorId SMALLSERIAL
  );

CREATE INDEX IF NOT EXISTS IX_PAYMENTS_BY_CREATETIME ON PAYMENTS (CreateTimestamp, Finished);

CREATE TABLE IF NOT EXISTS AMOUNTS (Amount DECIMAL NOT NULL);

CREATE INDEX IF NOT EXISTS IX_AMOUNTS ON AMOUNTS (Amount);

INSERT INTO DB_VERSIONS (VersionCode) VALUES ('START');
